### ISSUE TITLE
Provide a Docker image ready for production

### ISSUE THREAD

**Issue by loic-fejoz** [l-atelier-des-chercheurs/dodoc#377] opened 2019-07-14 14:06 UTC
Doing so would ease deployment of Do.Doc on shared environment. Providing a Dockefile is a preliminary step.
[I am on the way to get one working](https://github.com/loic-fejoz/dodoc/blob/dodoc2-dev-docker/Dockerfile). I will create a Pull Request when [the PDF export trouble](https://github.com/loic-fejoz/dodoc/issues/1) will be solved.

**Comment by louis-ev** [comment] 2023-11-08 14:22
duplicate of #630 
À voir si on arrive à remettre tout ça en marche pour la v10 !

**Closed** 2023-11-08 14:22 UTC
